services:
  postgres:
    image: postgres:latest
    container_name: gestorfinanceiro_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
        - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gestorfinanceiro_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      timeout: 5s

  adminer:
    image: adminer:latest
    container_name: gestorfinanceiro_adminer
    restart: always
    ports:
      - "8888:8080"
    networks:
      - gestorfinanceiro_network
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:

networks:
  gestorfinanceiro_network:
    driver: bridge
